//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Age_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Age_group()
        {
            this.Record = new HashSet<Record>();
            this.Parties = new HashSet<Parties>();
        }
    
        public int id { get; set; }
        public Nullable<int> age_start { get; set; }
        public Nullable<int> age_finish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parties> Parties { get; set; }
        public string AGE
        {
            get
            {
                return age_start + " - " + age_finish + " лет";
            }
        }
    }
}
