//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int id { get; set; }
        public int parties_id { get; set; }
        public int age_group_id { get; set; }
        public Nullable<System.DateTime> party_date { get; set; }
        public int user_id { get; set; }
    
        public virtual Age_group Age_group { get; set; }
        public virtual Parties Parties { get; set; }
        public virtual Users Users { get; set; }
    }
}
